// Code generated by entc, DO NOT EDIT.

package carcheckinout

const (
	// Label holds the string label denoting the carcheckinout type in the database.
	Label = "car_check_in_out"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the carcheckinout in the database.
	Table = "car_check_in_outs"
)

// Columns holds all SQL columns for carcheckinout fields.
var Columns = []string{
	FieldID,
}
