// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Ambulance is the predicate function for ambulance builders.
type Ambulance func(*sql.Selector)

// CarInspection is the predicate function for carinspection builders.
type CarInspection func(*sql.Selector)

// CarRepairrecord is the predicate function for carrepairrecord builders.
type CarRepairrecord func(*sql.Selector)

// Carregister is the predicate function for carregister builders.
type Carregister func(*sql.Selector)

// Deliver is the predicate function for deliver builders.
type Deliver func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
