// Code generated by entc, DO NOT EDIT.

package deliver

const (
	// Label holds the string label denoting the deliver type in the database.
	Label = "deliver"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the deliver in the database.
	Table = "delivers"
)

// Columns holds all SQL columns for deliver fields.
var Columns = []string{
	FieldID,
}
