// Code generated by entc, DO NOT EDIT.

package receive

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team07/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Receivename applies equality check predicate on the "receivename" field. It's identical to ReceivenameEQ.
func Receivename(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReceivename), v))
	})
}

// ReceivenameEQ applies the EQ predicate on the "receivename" field.
func ReceivenameEQ(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReceivename), v))
	})
}

// ReceivenameNEQ applies the NEQ predicate on the "receivename" field.
func ReceivenameNEQ(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReceivename), v))
	})
}

// ReceivenameIn applies the In predicate on the "receivename" field.
func ReceivenameIn(vs ...string) predicate.Receive {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Receive(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldReceivename), v...))
	})
}

// ReceivenameNotIn applies the NotIn predicate on the "receivename" field.
func ReceivenameNotIn(vs ...string) predicate.Receive {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Receive(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldReceivename), v...))
	})
}

// ReceivenameGT applies the GT predicate on the "receivename" field.
func ReceivenameGT(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReceivename), v))
	})
}

// ReceivenameGTE applies the GTE predicate on the "receivename" field.
func ReceivenameGTE(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReceivename), v))
	})
}

// ReceivenameLT applies the LT predicate on the "receivename" field.
func ReceivenameLT(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReceivename), v))
	})
}

// ReceivenameLTE applies the LTE predicate on the "receivename" field.
func ReceivenameLTE(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReceivename), v))
	})
}

// ReceivenameContains applies the Contains predicate on the "receivename" field.
func ReceivenameContains(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldReceivename), v))
	})
}

// ReceivenameHasPrefix applies the HasPrefix predicate on the "receivename" field.
func ReceivenameHasPrefix(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldReceivename), v))
	})
}

// ReceivenameHasSuffix applies the HasSuffix predicate on the "receivename" field.
func ReceivenameHasSuffix(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldReceivename), v))
	})
}

// ReceivenameEqualFold applies the EqualFold predicate on the "receivename" field.
func ReceivenameEqualFold(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldReceivename), v))
	})
}

// ReceivenameContainsFold applies the ContainsFold predicate on the "receivename" field.
func ReceivenameContainsFold(v string) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldReceivename), v))
	})
}

// HasReceiveid applies the HasEdge predicate on the "receiveid" edge.
func HasReceiveid() predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ReceiveidTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReceiveidTable, ReceiveidColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReceiveidWith applies the HasEdge predicate on the "receiveid" edge with a given conditions (other predicates).
func HasReceiveidWith(preds ...predicate.Transport) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ReceiveidInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReceiveidTable, ReceiveidColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Receive) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Receive) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Receive) predicate.Receive {
	return predicate.Receive(func(s *sql.Selector) {
		p(s.Not())
	})
}
