// Code generated by entc, DO NOT EDIT.

package distance

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team07/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Distance applies equality check predicate on the "Distance" field. It's identical to DistanceEQ.
func Distance(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDistance), v))
	})
}

// DistanceEQ applies the EQ predicate on the "Distance" field.
func DistanceEQ(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDistance), v))
	})
}

// DistanceNEQ applies the NEQ predicate on the "Distance" field.
func DistanceNEQ(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDistance), v))
	})
}

// DistanceIn applies the In predicate on the "Distance" field.
func DistanceIn(vs ...string) predicate.Distance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Distance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDistance), v...))
	})
}

// DistanceNotIn applies the NotIn predicate on the "Distance" field.
func DistanceNotIn(vs ...string) predicate.Distance {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Distance(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDistance), v...))
	})
}

// DistanceGT applies the GT predicate on the "Distance" field.
func DistanceGT(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDistance), v))
	})
}

// DistanceGTE applies the GTE predicate on the "Distance" field.
func DistanceGTE(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDistance), v))
	})
}

// DistanceLT applies the LT predicate on the "Distance" field.
func DistanceLT(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDistance), v))
	})
}

// DistanceLTE applies the LTE predicate on the "Distance" field.
func DistanceLTE(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDistance), v))
	})
}

// DistanceContains applies the Contains predicate on the "Distance" field.
func DistanceContains(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDistance), v))
	})
}

// DistanceHasPrefix applies the HasPrefix predicate on the "Distance" field.
func DistanceHasPrefix(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDistance), v))
	})
}

// DistanceHasSuffix applies the HasSuffix predicate on the "Distance" field.
func DistanceHasSuffix(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDistance), v))
	})
}

// DistanceEqualFold applies the EqualFold predicate on the "Distance" field.
func DistanceEqualFold(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDistance), v))
	})
}

// DistanceContainsFold applies the ContainsFold predicate on the "Distance" field.
func DistanceContainsFold(v string) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDistance), v))
	})
}

// HasDisid applies the HasEdge predicate on the "disid" edge.
func HasDisid() predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DisidTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DisidTable, DisidColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDisidWith applies the HasEdge predicate on the "disid" edge with a given conditions (other predicates).
func HasDisidWith(preds ...predicate.Carservice) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DisidInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DisidTable, DisidColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Distance) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Distance) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Distance) predicate.Distance {
	return predicate.Distance(func(s *sql.Selector) {
		p(s.Not())
	})
}
