// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/carrepairrecord"
	"github.com/team07/app/ent/predicate"
)

// CarRepairrecordDelete is the builder for deleting a CarRepairrecord entity.
type CarRepairrecordDelete struct {
	config
	hooks      []Hook
	mutation   *CarRepairrecordMutation
	predicates []predicate.CarRepairrecord
}

// Where adds a new predicate to the delete builder.
func (crd *CarRepairrecordDelete) Where(ps ...predicate.CarRepairrecord) *CarRepairrecordDelete {
	crd.predicates = append(crd.predicates, ps...)
	return crd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crd *CarRepairrecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(crd.hooks) == 0 {
		affected, err = crd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarRepairrecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			crd.mutation = mutation
			affected, err = crd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(crd.hooks) - 1; i >= 0; i-- {
			mut = crd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, crd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (crd *CarRepairrecordDelete) ExecX(ctx context.Context) int {
	n, err := crd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crd *CarRepairrecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: carrepairrecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carrepairrecord.FieldID,
			},
		},
	}
	if ps := crd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, crd.driver, _spec)
}

// CarRepairrecordDeleteOne is the builder for deleting a single CarRepairrecord entity.
type CarRepairrecordDeleteOne struct {
	crd *CarRepairrecordDelete
}

// Exec executes the deletion query.
func (crdo *CarRepairrecordDeleteOne) Exec(ctx context.Context) error {
	n, err := crdo.crd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{carrepairrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crdo *CarRepairrecordDeleteOne) ExecX(ctx context.Context) {
	crdo.crd.ExecX(ctx)
}
