// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/ambulance"
	"github.com/team07/app/ent/carstatus"
	"github.com/team07/app/ent/predicate"
)

// CarstatusUpdate is the builder for updating Carstatus entities.
type CarstatusUpdate struct {
	config
	hooks      []Hook
	mutation   *CarstatusMutation
	predicates []predicate.Carstatus
}

// Where adds a new predicate for the builder.
func (cu *CarstatusUpdate) Where(ps ...predicate.Carstatus) *CarstatusUpdate {
	cu.predicates = append(cu.predicates, ps...)
	return cu
}

// SetCarstatus sets the carstatus field.
func (cu *CarstatusUpdate) SetCarstatus(s string) *CarstatusUpdate {
	cu.mutation.SetCarstatus(s)
	return cu
}

// AddStatusofIDs adds the statusof edge to Ambulance by ids.
func (cu *CarstatusUpdate) AddStatusofIDs(ids ...int) *CarstatusUpdate {
	cu.mutation.AddStatusofIDs(ids...)
	return cu
}

// AddStatusof adds the statusof edges to Ambulance.
func (cu *CarstatusUpdate) AddStatusof(a ...*Ambulance) *CarstatusUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.AddStatusofIDs(ids...)
}

// Mutation returns the CarstatusMutation object of the builder.
func (cu *CarstatusUpdate) Mutation() *CarstatusMutation {
	return cu.mutation
}

// RemoveStatusofIDs removes the statusof edge to Ambulance by ids.
func (cu *CarstatusUpdate) RemoveStatusofIDs(ids ...int) *CarstatusUpdate {
	cu.mutation.RemoveStatusofIDs(ids...)
	return cu
}

// RemoveStatusof removes statusof edges to Ambulance.
func (cu *CarstatusUpdate) RemoveStatusof(a ...*Ambulance) *CarstatusUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cu.RemoveStatusofIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (cu *CarstatusUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarstatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CarstatusUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CarstatusUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CarstatusUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CarstatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   carstatus.Table,
			Columns: carstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carstatus.FieldID,
			},
		},
	}
	if ps := cu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Carstatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: carstatus.FieldCarstatus,
		})
	}
	if nodes := cu.mutation.RemovedStatusofIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carstatus.StatusofTable,
			Columns: []string{carstatus.StatusofColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: ambulance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.StatusofIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carstatus.StatusofTable,
			Columns: []string{carstatus.StatusofColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: ambulance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carstatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CarstatusUpdateOne is the builder for updating a single Carstatus entity.
type CarstatusUpdateOne struct {
	config
	hooks    []Hook
	mutation *CarstatusMutation
}

// SetCarstatus sets the carstatus field.
func (cuo *CarstatusUpdateOne) SetCarstatus(s string) *CarstatusUpdateOne {
	cuo.mutation.SetCarstatus(s)
	return cuo
}

// AddStatusofIDs adds the statusof edge to Ambulance by ids.
func (cuo *CarstatusUpdateOne) AddStatusofIDs(ids ...int) *CarstatusUpdateOne {
	cuo.mutation.AddStatusofIDs(ids...)
	return cuo
}

// AddStatusof adds the statusof edges to Ambulance.
func (cuo *CarstatusUpdateOne) AddStatusof(a ...*Ambulance) *CarstatusUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.AddStatusofIDs(ids...)
}

// Mutation returns the CarstatusMutation object of the builder.
func (cuo *CarstatusUpdateOne) Mutation() *CarstatusMutation {
	return cuo.mutation
}

// RemoveStatusofIDs removes the statusof edge to Ambulance by ids.
func (cuo *CarstatusUpdateOne) RemoveStatusofIDs(ids ...int) *CarstatusUpdateOne {
	cuo.mutation.RemoveStatusofIDs(ids...)
	return cuo
}

// RemoveStatusof removes statusof edges to Ambulance.
func (cuo *CarstatusUpdateOne) RemoveStatusof(a ...*Ambulance) *CarstatusUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return cuo.RemoveStatusofIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (cuo *CarstatusUpdateOne) Save(ctx context.Context) (*Carstatus, error) {

	var (
		err  error
		node *Carstatus
	)
	if len(cuo.hooks) == 0 {
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarstatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CarstatusUpdateOne) SaveX(ctx context.Context) *Carstatus {
	c, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

// Exec executes the query on the entity.
func (cuo *CarstatusUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CarstatusUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CarstatusUpdateOne) sqlSave(ctx context.Context) (c *Carstatus, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   carstatus.Table,
			Columns: carstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carstatus.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Carstatus.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := cuo.mutation.Carstatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: carstatus.FieldCarstatus,
		})
	}
	if nodes := cuo.mutation.RemovedStatusofIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carstatus.StatusofTable,
			Columns: []string{carstatus.StatusofColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: ambulance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.StatusofIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   carstatus.StatusofTable,
			Columns: []string{carstatus.StatusofColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: ambulance.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	c = &Carstatus{config: cuo.config}
	_spec.Assign = c.assignValues
	_spec.ScanValues = c.scanValues()
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{carstatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return c, nil
}
