// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/carservice"
)

// CarserviceCreate is the builder for creating a Carservice entity.
type CarserviceCreate struct {
	config
	mutation *CarserviceMutation
	hooks    []Hook
}

// Mutation returns the CarserviceMutation object of the builder.
func (cc *CarserviceCreate) Mutation() *CarserviceMutation {
	return cc.mutation
}

// Save creates the Carservice in the database.
func (cc *CarserviceCreate) Save(ctx context.Context) (*Carservice, error) {
	var (
		err  error
		node *Carservice
	)
	if len(cc.hooks) == 0 {
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CarserviceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CarserviceCreate) SaveX(ctx context.Context) *Carservice {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cc *CarserviceCreate) sqlSave(ctx context.Context) (*Carservice, error) {
	c, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	c.ID = int(id)
	return c, nil
}

func (cc *CarserviceCreate) createSpec() (*Carservice, *sqlgraph.CreateSpec) {
	var (
		c     = &Carservice{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: carservice.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: carservice.FieldID,
			},
		}
	)
	return c, _spec
}
