// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/servicetype"
)

// ServicetypeCreate is the builder for creating a Servicetype entity.
type ServicetypeCreate struct {
	config
	mutation *ServicetypeMutation
	hooks    []Hook
}

// Mutation returns the ServicetypeMutation object of the builder.
func (sc *ServicetypeCreate) Mutation() *ServicetypeMutation {
	return sc.mutation
}

// Save creates the Servicetype in the database.
func (sc *ServicetypeCreate) Save(ctx context.Context) (*Servicetype, error) {
	var (
		err  error
		node *Servicetype
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServicetypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ServicetypeCreate) SaveX(ctx context.Context) *Servicetype {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *ServicetypeCreate) sqlSave(ctx context.Context) (*Servicetype, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *ServicetypeCreate) createSpec() (*Servicetype, *sqlgraph.CreateSpec) {
	var (
		s     = &Servicetype{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: servicetype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: servicetype.FieldID,
			},
		}
	)
	return s, _spec
}
