// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/carservice"
	"github.com/team07/app/ent/urgent"
)

// UrgentCreate is the builder for creating a Urgent entity.
type UrgentCreate struct {
	config
	mutation *UrgentMutation
	hooks    []Hook
}

// SetUrgent sets the urgent field.
func (uc *UrgentCreate) SetUrgent(s string) *UrgentCreate {
	uc.mutation.SetUrgent(s)
	return uc
}

// AddUrgentidIDs adds the urgentid edge to Carservice by ids.
func (uc *UrgentCreate) AddUrgentidIDs(ids ...int) *UrgentCreate {
	uc.mutation.AddUrgentidIDs(ids...)
	return uc
}

// AddUrgentid adds the urgentid edges to Carservice.
func (uc *UrgentCreate) AddUrgentid(c ...*Carservice) *UrgentCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddUrgentidIDs(ids...)
}

// Mutation returns the UrgentMutation object of the builder.
func (uc *UrgentCreate) Mutation() *UrgentMutation {
	return uc.mutation
}

// Save creates the Urgent in the database.
func (uc *UrgentCreate) Save(ctx context.Context) (*Urgent, error) {
	if _, ok := uc.mutation.Urgent(); !ok {
		return nil, &ValidationError{Name: "urgent", err: errors.New("ent: missing required field \"urgent\"")}
	}
	if v, ok := uc.mutation.Urgent(); ok {
		if err := urgent.UrgentValidator(v); err != nil {
			return nil, &ValidationError{Name: "urgent", err: fmt.Errorf("ent: validator failed for field \"urgent\": %w", err)}
		}
	}
	var (
		err  error
		node *Urgent
	)
	if len(uc.hooks) == 0 {
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UrgentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uc.mutation = mutation
			node, err = uc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UrgentCreate) SaveX(ctx context.Context) *Urgent {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UrgentCreate) sqlSave(ctx context.Context) (*Urgent, error) {
	u, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	u.ID = int(id)
	return u, nil
}

func (uc *UrgentCreate) createSpec() (*Urgent, *sqlgraph.CreateSpec) {
	var (
		u     = &Urgent{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: urgent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: urgent.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.Urgent(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: urgent.FieldUrgent,
		})
		u.Urgent = value
	}
	if nodes := uc.mutation.UrgentidIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   urgent.UrgentidTable,
			Columns: []string{urgent.UrgentidColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: carservice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return u, _spec
}
