// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/team07/app/ent/urgent"
)

// Urgent is the model entity for the Urgent schema.
type Urgent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Urgent holds the value of the "urgent" field.
	Urgent string `json:"urgent,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UrgentQuery when eager-loading is set.
	Edges UrgentEdges `json:"edges"`
}

// UrgentEdges holds the relations/edges for other nodes in the graph.
type UrgentEdges struct {
	// Urgentid holds the value of the urgentid edge.
	Urgentid []*Carservice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UrgentidOrErr returns the Urgentid value or an error if the edge
// was not loaded in eager-loading.
func (e UrgentEdges) UrgentidOrErr() ([]*Carservice, error) {
	if e.loadedTypes[0] {
		return e.Urgentid, nil
	}
	return nil, &NotLoadedError{edge: "urgentid"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Urgent) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // urgent
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Urgent fields.
func (u *Urgent) assignValues(values ...interface{}) error {
	if m, n := len(values), len(urgent.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	u.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field urgent", values[0])
	} else if value.Valid {
		u.Urgent = value.String
	}
	return nil
}

// QueryUrgentid queries the urgentid edge of the Urgent.
func (u *Urgent) QueryUrgentid() *CarserviceQuery {
	return (&UrgentClient{config: u.config}).QueryUrgentid(u)
}

// Update returns a builder for updating this Urgent.
// Note that, you need to call Urgent.Unwrap() before calling this method, if this Urgent
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *Urgent) Update() *UrgentUpdateOne {
	return (&UrgentClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (u *Urgent) Unwrap() *Urgent {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: Urgent is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *Urgent) String() string {
	var builder strings.Builder
	builder.WriteString("Urgent(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", urgent=")
	builder.WriteString(u.Urgent)
	builder.WriteByte(')')
	return builder.String()
}

// Urgents is a parsable slice of Urgent.
type Urgents []*Urgent

func (u Urgents) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
