// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team07/app/ent/urgent"
)

// UrgentCreate is the builder for creating a Urgent entity.
type UrgentCreate struct {
	config
	mutation *UrgentMutation
	hooks    []Hook
}

// Mutation returns the UrgentMutation object of the builder.
func (uc *UrgentCreate) Mutation() *UrgentMutation {
	return uc.mutation
}

// Save creates the Urgent in the database.
func (uc *UrgentCreate) Save(ctx context.Context) (*Urgent, error) {
	var (
		err  error
		node *Urgent
	)
	if len(uc.hooks) == 0 {
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UrgentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uc.mutation = mutation
			node, err = uc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UrgentCreate) SaveX(ctx context.Context) *Urgent {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UrgentCreate) sqlSave(ctx context.Context) (*Urgent, error) {
	u, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	u.ID = int(id)
	return u, nil
}

func (uc *UrgentCreate) createSpec() (*Urgent, *sqlgraph.CreateSpec) {
	var (
		u     = &Urgent{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: urgent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: urgent.FieldID,
			},
		}
	)
	return u, _spec
}
