// Code generated by entc, DO NOT EDIT.

package inspectionresult

const (
	// Label holds the string label denoting the inspectionresult type in the database.
	Label = "inspection_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResultName holds the string denoting the result_name field in the database.
	FieldResultName = "result_name"

	// EdgeCarinspections holds the string denoting the carinspections edge name in mutations.
	EdgeCarinspections = "carinspections"
	// EdgeStatusof holds the string denoting the statusof edge name in mutations.
	EdgeStatusof = "statusof"
	// EdgeJobposition holds the string denoting the jobposition edge name in mutations.
	EdgeJobposition = "jobposition"

	// Table holds the table name of the inspectionresult in the database.
	Table = "inspection_results"
	// CarinspectionsTable is the table the holds the carinspections relation/edge.
	CarinspectionsTable = "car_inspections"
	// CarinspectionsInverseTable is the table name for the CarInspection entity.
	// It exists in this package in order to avoid circular dependency with the "carinspection" package.
	CarinspectionsInverseTable = "car_inspections"
	// CarinspectionsColumn is the table column denoting the carinspections relation/edge.
	CarinspectionsColumn = "inspectionresult_id"
	// StatusofTable is the table the holds the statusof relation/edge.
	StatusofTable = "ambulances"
	// StatusofInverseTable is the table name for the Ambulance entity.
	// It exists in this package in order to avoid circular dependency with the "ambulance" package.
	StatusofInverseTable = "ambulances"
	// StatusofColumn is the table column denoting the statusof relation/edge.
	StatusofColumn = "carstatus_id"
	// JobpositionTable is the table the holds the jobposition relation/edge.
	JobpositionTable = "inspection_results"
	// JobpositionInverseTable is the table name for the JobPosition entity.
	// It exists in this package in order to avoid circular dependency with the "jobposition" package.
	JobpositionInverseTable = "job_positions"
	// JobpositionColumn is the table column denoting the jobposition relation/edge.
	JobpositionColumn = "jobposition_id"
)

// Columns holds all SQL columns for inspectionresult fields.
var Columns = []string{
	FieldID,
	FieldResultName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the InspectionResult type.
var ForeignKeys = []string{
	"jobposition_id",
}

var (
	// ResultNameValidator is a validator for the "result_name" field. It is called by the builders before save.
	ResultNameValidator func(string) error
)
