// Code generated by entc, DO NOT EDIT.

package send

const (
	// Label holds the string label denoting the send type in the database.
	Label = "send"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSendname holds the string denoting the sendname field in the database.
	FieldSendname = "sendname"

	// EdgeSendid holds the string denoting the sendid edge name in mutations.
	EdgeSendid = "sendid"

	// Table holds the table name of the send in the database.
	Table = "sends"
	// SendidTable is the table the holds the sendid relation/edge.
	SendidTable = "transports"
	// SendidInverseTable is the table name for the Transport entity.
	// It exists in this package in order to avoid circular dependency with the "transport" package.
	SendidInverseTable = "transports"
	// SendidColumn is the table column denoting the sendid relation/edge.
	SendidColumn = "sendid"
)

// Columns holds all SQL columns for send fields.
var Columns = []string{
	FieldID,
	FieldSendname,
}
