// Code generated by entc, DO NOT EDIT.

package carrepairrecord

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team07/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Datetime applies equality check predicate on the "datetime" field. It's identical to DatetimeEQ.
func Datetime(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDatetime), v))
	})
}

// Repairdetail applies equality check predicate on the "repairdetail" field. It's identical to RepairdetailEQ.
func Repairdetail(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRepairdetail), v))
	})
}

// Repaircost applies equality check predicate on the "repaircost" field. It's identical to RepaircostEQ.
func Repaircost(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRepaircost), v))
	})
}

// Carmaintenance applies equality check predicate on the "carmaintenance" field. It's identical to CarmaintenanceEQ.
func Carmaintenance(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCarmaintenance), v))
	})
}

// DatetimeEQ applies the EQ predicate on the "datetime" field.
func DatetimeEQ(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDatetime), v))
	})
}

// DatetimeNEQ applies the NEQ predicate on the "datetime" field.
func DatetimeNEQ(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDatetime), v))
	})
}

// DatetimeIn applies the In predicate on the "datetime" field.
func DatetimeIn(vs ...time.Time) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDatetime), v...))
	})
}

// DatetimeNotIn applies the NotIn predicate on the "datetime" field.
func DatetimeNotIn(vs ...time.Time) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDatetime), v...))
	})
}

// DatetimeGT applies the GT predicate on the "datetime" field.
func DatetimeGT(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDatetime), v))
	})
}

// DatetimeGTE applies the GTE predicate on the "datetime" field.
func DatetimeGTE(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDatetime), v))
	})
}

// DatetimeLT applies the LT predicate on the "datetime" field.
func DatetimeLT(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDatetime), v))
	})
}

// DatetimeLTE applies the LTE predicate on the "datetime" field.
func DatetimeLTE(v time.Time) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDatetime), v))
	})
}

// RepairdetailEQ applies the EQ predicate on the "repairdetail" field.
func RepairdetailEQ(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailNEQ applies the NEQ predicate on the "repairdetail" field.
func RepairdetailNEQ(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailIn applies the In predicate on the "repairdetail" field.
func RepairdetailIn(vs ...string) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRepairdetail), v...))
	})
}

// RepairdetailNotIn applies the NotIn predicate on the "repairdetail" field.
func RepairdetailNotIn(vs ...string) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRepairdetail), v...))
	})
}

// RepairdetailGT applies the GT predicate on the "repairdetail" field.
func RepairdetailGT(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailGTE applies the GTE predicate on the "repairdetail" field.
func RepairdetailGTE(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailLT applies the LT predicate on the "repairdetail" field.
func RepairdetailLT(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailLTE applies the LTE predicate on the "repairdetail" field.
func RepairdetailLTE(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailContains applies the Contains predicate on the "repairdetail" field.
func RepairdetailContains(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailHasPrefix applies the HasPrefix predicate on the "repairdetail" field.
func RepairdetailHasPrefix(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailHasSuffix applies the HasSuffix predicate on the "repairdetail" field.
func RepairdetailHasSuffix(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailEqualFold applies the EqualFold predicate on the "repairdetail" field.
func RepairdetailEqualFold(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRepairdetail), v))
	})
}

// RepairdetailContainsFold applies the ContainsFold predicate on the "repairdetail" field.
func RepairdetailContainsFold(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRepairdetail), v))
	})
}

// RepaircostEQ applies the EQ predicate on the "repaircost" field.
func RepaircostEQ(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRepaircost), v))
	})
}

// RepaircostNEQ applies the NEQ predicate on the "repaircost" field.
func RepaircostNEQ(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRepaircost), v))
	})
}

// RepaircostIn applies the In predicate on the "repaircost" field.
func RepaircostIn(vs ...int) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRepaircost), v...))
	})
}

// RepaircostNotIn applies the NotIn predicate on the "repaircost" field.
func RepaircostNotIn(vs ...int) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRepaircost), v...))
	})
}

// RepaircostGT applies the GT predicate on the "repaircost" field.
func RepaircostGT(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRepaircost), v))
	})
}

// RepaircostGTE applies the GTE predicate on the "repaircost" field.
func RepaircostGTE(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRepaircost), v))
	})
}

// RepaircostLT applies the LT predicate on the "repaircost" field.
func RepaircostLT(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRepaircost), v))
	})
}

// RepaircostLTE applies the LTE predicate on the "repaircost" field.
func RepaircostLTE(v int) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRepaircost), v))
	})
}

// CarmaintenanceEQ applies the EQ predicate on the "carmaintenance" field.
func CarmaintenanceEQ(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceNEQ applies the NEQ predicate on the "carmaintenance" field.
func CarmaintenanceNEQ(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceIn applies the In predicate on the "carmaintenance" field.
func CarmaintenanceIn(vs ...string) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCarmaintenance), v...))
	})
}

// CarmaintenanceNotIn applies the NotIn predicate on the "carmaintenance" field.
func CarmaintenanceNotIn(vs ...string) predicate.CarRepairrecord {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCarmaintenance), v...))
	})
}

// CarmaintenanceGT applies the GT predicate on the "carmaintenance" field.
func CarmaintenanceGT(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceGTE applies the GTE predicate on the "carmaintenance" field.
func CarmaintenanceGTE(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceLT applies the LT predicate on the "carmaintenance" field.
func CarmaintenanceLT(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceLTE applies the LTE predicate on the "carmaintenance" field.
func CarmaintenanceLTE(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceContains applies the Contains predicate on the "carmaintenance" field.
func CarmaintenanceContains(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceHasPrefix applies the HasPrefix predicate on the "carmaintenance" field.
func CarmaintenanceHasPrefix(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceHasSuffix applies the HasSuffix predicate on the "carmaintenance" field.
func CarmaintenanceHasSuffix(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceEqualFold applies the EqualFold predicate on the "carmaintenance" field.
func CarmaintenanceEqualFold(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCarmaintenance), v))
	})
}

// CarmaintenanceContainsFold applies the ContainsFold predicate on the "carmaintenance" field.
func CarmaintenanceContainsFold(v string) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCarmaintenance), v))
	})
}

// HasKeeper applies the HasEdge predicate on the "keeper" edge.
func HasKeeper() predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(KeeperTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeeperTable, KeeperColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeeperWith applies the HasEdge predicate on the "keeper" edge with a given conditions (other predicates).
func HasKeeperWith(preds ...predicate.Repairing) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(KeeperInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeeperTable, KeeperColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCarinspection applies the HasEdge predicate on the "carinspection" edge.
func HasCarinspection() predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CarinspectionTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CarinspectionTable, CarinspectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCarinspectionWith applies the HasEdge predicate on the "carinspection" edge with a given conditions (other predicates).
func HasCarinspectionWith(preds ...predicate.CarInspection) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CarinspectionInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CarinspectionTable, CarinspectionColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.CarRepairrecord) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.CarRepairrecord) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CarRepairrecord) predicate.CarRepairrecord {
	return predicate.CarRepairrecord(func(s *sql.Selector) {
		p(s.Not())
	})
}
