/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersTransport
 */
export interface ControllersTransport {
    /**
     * 
     * @type {number}
     * @memberof ControllersTransport
     */
    ambulanceID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersTransport
     */
    receiveID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersTransport
     */
    sendID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersTransport
     */
    userID?: number;
}

export function ControllersTransportFromJSON(json: any): ControllersTransport {
    return ControllersTransportFromJSONTyped(json, false);
}

export function ControllersTransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersTransport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ambulanceID': !exists(json, 'ambulanceID') ? undefined : json['ambulanceID'],
        'receiveID': !exists(json, 'receiveID') ? undefined : json['receiveID'],
        'sendID': !exists(json, 'sendID') ? undefined : json['sendID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersTransportToJSON(value?: ControllersTransport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ambulanceID': value.ambulanceID,
        'receiveID': value.receiveID,
        'sendID': value.sendID,
        'userID': value.userID,
    };
}


