/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntClassinsuranceEdges,
    EntClassinsuranceEdgesFromJSON,
    EntClassinsuranceEdgesFromJSONTyped,
    EntClassinsuranceEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClassinsurance
 */
export interface EntClassinsurance {
    /**
     * Classofinsurance holds the value of the "classofinsurance" field.
     * @type {string}
     * @memberof EntClassinsurance
     */
    classofinsurance?: string;
    /**
     * 
     * @type {EntClassinsuranceEdges}
     * @memberof EntClassinsurance
     */
    edges?: EntClassinsuranceEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntClassinsurance
     */
    id?: number;
}

export function EntClassinsuranceFromJSON(json: any): EntClassinsurance {
    return EntClassinsuranceFromJSONTyped(json, false);
}

export function EntClassinsuranceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClassinsurance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classofinsurance': !exists(json, 'classofinsurance') ? undefined : json['classofinsurance'],
        'edges': !exists(json, 'edges') ? undefined : EntClassinsuranceEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntClassinsuranceToJSON(value?: EntClassinsurance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'classofinsurance': value.classofinsurance,
        'edges': EntClassinsuranceEdgesToJSON(value.edges),
        'id': value.id,
    };
}


