/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCarserviceEdges,
    EntCarserviceEdgesFromJSON,
    EntCarserviceEdgesFromJSONTyped,
    EntCarserviceEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCarservice
 */
export interface EntCarservice {
    /**
     * Datetime holds the value of the "Datetime" field.
     * @type {string}
     * @memberof EntCarservice
     */
    datetime?: string;
    /**
     * Customer holds the value of the "customer" field.
     * @type {string}
     * @memberof EntCarservice
     */
    customer?: string;
    /**
     * 
     * @type {EntCarserviceEdges}
     * @memberof EntCarservice
     */
    edges?: EntCarserviceEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCarservice
     */
    id?: number;
    /**
     * Information holds the value of the "information" field.
     * @type {string}
     * @memberof EntCarservice
     */
    information?: string;
    /**
     * Location holds the value of the "location" field.
     * @type {string}
     * @memberof EntCarservice
     */
    location?: string;
}

export function EntCarserviceFromJSON(json: any): EntCarservice {
    return EntCarserviceFromJSONTyped(json, false);
}

export function EntCarserviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCarservice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datetime': !exists(json, 'Datetime') ? undefined : json['Datetime'],
        'customer': !exists(json, 'customer') ? undefined : json['customer'],
        'edges': !exists(json, 'edges') ? undefined : EntCarserviceEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'information': !exists(json, 'information') ? undefined : json['information'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function EntCarserviceToJSON(value?: EntCarservice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Datetime': value.datetime,
        'customer': value.customer,
        'edges': EntCarserviceEdgesToJSON(value.edges),
        'id': value.id,
        'information': value.information,
        'location': value.location,
    };
}


